Chore/4021 migrate ra to vite
AdaptiveConsulting/ReactiveAnalytics pull request #210
Opened 2022-11-14 16:58 UTC by Clark-Adaptive

Very rudimentary migration that uses Vite to bundle instead of React-App-Rewired.

Most of the assets are loaded when the client connects to the server.

Still has some bugs.

2022-11-16 12:44 UTC, algreasley requested changes
this is a great effort .. just a few details to iron out to complete the transition to vite

2022-11-16 12:44 UTC, algreasley commented on .gitignore
> +# distributable
I'd pop this in the `# production` section below with a (slightly modified) build exclusion so it is like this:
```
build/
dist/
```

see https://git-scm.com/docs/gitignore

2022-11-16 12:44 UTC, algreasley commented on client/.gitignore
> +/dist
should not need here as well as root ignore file

2022-11-16 12:44 UTC, algreasley commented on client/package.json
> +    "graphql": "^16.6.0",
hmm - not sure we want to jump major versions here, without corresponding changes in the 'server' package and without being able to test it locally ..

2022-11-16 12:44 UTC, algreasley commented on client/tsconfig.json
> +    "jsx": "react",
hmm - React bumped to v17 in package.json .. can we use "react-jsx" now?

2022-11-16 12:44 UTC, algreasley commented on yarn.lock
> +"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.16.0":
should be no changes to root yarn.lock - in fact, we should review whether we need a root yarn.lock at all - it depends whether we can restore yarn workspaces when we have sorted out the new build & deployment structure for RA using the same approach as on RT

2022-11-16 12:44 UTC, algreasley commented on client/package.json
> +    "react": "^17",
umm .. not a problem, but this may have other consequences .. but it is syncing up with RT so that's a good thing .. I see the `vite.config` is synced up with R17, but perhaps not the `tsconfig.json` ?

2022-11-16 12:44 UTC, algreasley commented on client/package.json
> +    "start": "vite",
we are not done, btw, until we have remove react-app-rewired from the devDependencies ..
I believe there is a corresponding "https" setting for vite, but don't bother keeping this in here unless we are sure we need it (usually requires certificate files etc.) .. something to look into briefly, I'd say
.. the start:dev looks useful for local testing, btw

2022-11-16 12:44 UTC, algreasley commented on client/package.json
>      "test": "react-app-rewired test --env=jsdom",
I think best approach is to port across any basic test setup from RT .. I want to look at vitest, so if that is going to be quicker (given we have no client tests atm, anyway) then we could consider switching to that instead .. I am looking at the test setup in RT so let's catch up this week on this.
.. we should have at least one test to prove this is actually working.

2022-11-16 12:44 UTC, algreasley commented on client/package.json
>      "eject": "react-app-rewired eject",
we won't need an `"eject"` now ... we have basically 'hard-ejected' by switching to vite 😆

2022-11-16 12:44 UTC, algreasley commented on client/package.json
> +    "graphql": "^16.6.0"
hmm - see above - also, I would question why we need a "resolutions" entry here .. it might be historical

2022-11-16 12:44 UTC, algreasley commented on client/package.json
> +    "graphql": "^16.6.0",
ah, we can test with `yarn start:dev` as below ...

2022-11-16 12:52 UTC, algreasley commented on client/package.json
>      "test": "react-app-rewired test --env=jsdom",
on second thoughts, just switch to "vite test" .. I'll add a separate ticket to deal with the client testing .. and we'll go with vitest straight off the bat, and then port back over to RT, although I don't think it should be much effort to switch acc to recent discussion on Slack `#dev-html5` .. sound ok?

2022-11-16 19:59 UTC, Clark-Adaptive commented on client/tsconfig.json
> +    "jsx": "react",
We are going back down to React 16.8.6 so it will be "jsx": "react"

2022-11-16 20:03 UTC, Clark-Adaptive commented on client/package.json
> +    "start": "vite",
I am removing react-app-rewired in my next commit

2022-11-16 20:13 UTC, Clark-Adaptive commented on client/package.json
> +    "graphql": "^16.6.0"
I removed the resolutions attribute, it was not really doing anything when we upgraded to graphql 16.6.0

2022-11-16 20:14 UTC, Clark-Adaptive commented on client/package.json
> +    "graphql": "^16.6.0",
We have decided we need to upgrade graphql in order to resolve types.

2022-11-16 20:14 UTC, Clark-Adaptive commented on .gitignore
> +# distributable
will add in next commit

2022-11-16 20:15 UTC, Clark-Adaptive commented on client/.gitignore
> +/dist
will add in next commit

2022-11-16 20:34 UTC, bruceharris commented on client/.env
> +VITE_REACT_APP_ANALYTICS_SERVER_HOST=localhost:4000
the `VITE_` prefix replaces the `REACT_APP_` prefix, so we can remove `REACT_APP_` from these var names

2022-11-16 20:41 UTC, Clark-Adaptive commented on client/.env
> +VITE_REACT_APP_ANALYTICS_SERVER_HOST=localhost:4000
will do

2022-11-16 20:47 UTC, bruceharris commented on client/src/helpers/uriHelper.ts
> +const isSecure = import.meta.env.REACT_APP_ANALYTICS_SERVER_HTTPS || window.location.protocol === 'https:'
this env var won't work unless prefixed by `VITE_` - see https://vitejs.dev/guide/env-and-mode.html#env-files

2022-11-16 20:52 UTC, bruceharris commented on client/src/index.tsx
> +console.log('test')
we should probably remove this console.log. before merging

2022-11-16 20:53 UTC, Clark-Adaptive commented on client/src/helpers/uriHelper.ts
> +const isSecure = import.meta.env.REACT_APP_ANALYTICS_SERVER_HTTPS || window.location.protocol === 'https:'
I'm a bit confused about what you mean, I believe I did prefix the environment variables with VITE_?

2022-11-16 20:53 UTC, Clark-Adaptive commented on client/src/index.tsx
> +console.log('test')
right, good catch

2022-11-16 20:53 UTC, bruceharris commented on client/vite.config.ts
> +export default defineConfig({
@algreasley alluded to this above, but I think we'll need plugins in here to copy and do string substitution for the various manifest files.

2022-11-16 22:18 UTC, bruceharris commented on client/src/helpers/uriHelper.ts
> +const isSecure = import.meta.env.REACT_APP_ANALYTICS_SERVER_HTTPS || window.location.protocol === 'https:'
yes, please disregard, I commented on an earlier version of the code before you added the prefix, thanks!

2022-11-16 22:19 UTC, bruceharris commented on client/vite.config.ts
> +export default defineConfig({
Yup, no worries, see https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/src/client/vite.config.ts#L169-L244

2022-11-17 13:37 UTC, algreasley commented on client/tsconfig.json
> +    "jsx": "react",
y, that's fine for now .. we'll be bumping to R17 pretty soon as part of the general package bumping session - this will fix Downshift incompatibility discussed recently

2022-11-17 13:42 UTC, algreasley commented on client/package.json
> +    "start": "vite",
as you have removed `react-app-rewired` from dev dependencies, we should sync w RT here and just set this to "jest" .. that is a reasonable placeholder that works until we try out vitest

2022-11-22 13:15 UTC, bruceharris commented on README.md
> +### Changes made in Chore/4021 migrate RA to vite
Nice summary! Perhaps we should move this to a `CHANGELOG.md` and link to it from here.

2022-11-22 13:18 UTC, bruceharris commented on client/package.json
> +    "vite": "^2.8.6",
hmm, I know this is a bit late to be asking this now, apologies I didn't notice earlier, but we ought to be using the latest version of Vite. At the very least we should be using the latest in the 2.* major version, but if we're going to all this effort to port to Vite, we really ought to be on 3.*

2022-11-22 13:26 UTC, bruceharris commented on client/vite.config.ts
> +  const host_url = `${scheme}://${process.env.HOST || 'localhost'}:${process.env.PORT || '3005'}`
this should be `hostUrl` in `camelCase` for consistency

2022-11-22 13:31 UTC, bruceharris commented on client/vite.config.ts
> +  // const envSuffix = (process.env.ENVIRONMENT || 'local').toUpperCase()
let's please remove commented out code, thanks!

2022-11-23 15:20 UTC, Clark-Adaptive commented on client/vite.config.ts
> +  // const envSuffix = (process.env.ENVIRONMENT || 'local').toUpperCase()
👍 good catch, will remove in next commit

2022-11-23 15:24 UTC, Clark-Adaptive commented on README.md
> +### Changes made in Chore/4021 migrate RA to vite
Yes, that is a good idea 👍

2022-11-23 15:26 UTC, Clark-Adaptive commented on client/vite.config.ts
> +  const host_url = `${scheme}://${process.env.HOST || 'localhost'}:${process.env.PORT || '3005'}`
👍 will fix in next commit

2022-11-23 15:52 UTC, Clark-Adaptive commented on client/public/manifest.json
>  {
Actually, as @algreasley mentioned in standup, due to Nginx expecting placeholders, we may need to stick with the original templates and project structure with the template folders, I will be reverting this in the next commit.

2022-11-24 17:50 UTC, algreasley submitted a review, later dismissed

2022-11-24 17:50 UTC, algreasley commented on client/src/containers/search/components/SearchInput.tsx
> +      onInputValueChange={inputValue => onTextChange(inputValue)}
this fixes the react console error when you click on the stock input

2022-11-24 17:54 UTC, algreasley commented on package.json
>    },
this is not a functioning yarn workspaces setup .. the builds require local yarn contexts and lock files (for the docker build - does yarn ci ..) so I have switched this off. When we migrate this over to a RT-like build, we might be able to restore the workspaces, but perhaps not as syncing with RT means using npm (open to discussion on this, as npm is still not exactly great, in my experience .. and some are using yarn 2+ or pnpm .. worth a dev huddle, I would say)

2022-11-28 18:00 UTC, bruceharris submitted a review, later dismissed
👍

2022-11-29 13:10 UTC, algreasley reviewed
that's pretty much it ... few minor tidy-ups

2022-11-29 13:10 UTC, algreasley commented on client/package.json
> +    "vite-plugin-babel-macros": "^1.0.6"
small thing .. but this should be a devDependency

2022-11-29 13:10 UTC, algreasley commented on client/vite.config.ts
> +  const plugins = [react(), graphql(), copyPlugin(isDev), macrosPlugin()]
ah, I meant to comment earlier .. I think the macrosPlugin should probably be dev-only (cross-check on their docs)

2022-11-29 13:10 UTC, algreasley commented on client/vite.config.ts
> +    plugins: plugins,
minor .. collapse this

2022-11-29 13:10 UTC, algreasley commented on native/App.js
> +import { ThemeProvider } from 'styled-components/macro'
I would undo these ... just leave native/ alone I think as it is dormant / unmaintained

2022-11-29 15:08 UTC, Clark-Adaptive commented on client/package.json
> +    "vite-plugin-babel-macros": "^1.0.6"
👍

2022-11-29 15:10 UTC, Clark-Adaptive commented on client/vite.config.ts
> +  const plugins = [react(), graphql(), copyPlugin(isDev), macrosPlugin()]
I added a conditional to only push macrosPlugin if isDev is true

2022-11-29 15:15 UTC, Clark-Adaptive commented on native/App.js
> +import { ThemeProvider } from 'styled-components/macro'
👍 reverted all changes in the native folder

2022-11-29 15:18 UTC, Clark-Adaptive commented on client/vite.config.ts
> +    plugins: plugins,
Do you mean to just insert the array directly into plugins?

  return defineConfig({
    plugins: [react(), graphql(), copyPlugin(isDev), macrosPlugin()]

2022-11-29 20:44 UTC, algreasley commented on client/vite.config.ts
> +  const plugins = [react(), graphql(), copyPlugin(isDev), macrosPlugin()]
but reverted after our conversation .. you were right, given the form of the import statements ...

2022-11-29 20:45 UTC, algreasley commented on client/vite.config.ts
> +    plugins: plugins,
no, I should have been more precise .. I meant just use plugins (ref our convo a few days back, no need for var: var in modern ES ..) but not important

2022-11-29 20:46 UTC, algreasley approved these changes
good stuff - really happy to see this go in, and RA start to align to the RT patterns

2022-11-29 20:50 UTC, merged